from .ovf2 import OVF2_FIRST_LINE, \
    HEADER_READ_BYTES, HEADER_DTYPES, HEADER_BEGIN_MARKER, HEADER_END_MARKER, \
    DATA_BEGIN_MARKER, DATA_END_MARKER, \
    BINARY4_FLAG, BINARY8_FLAG

from .hdf5 import DETECT_OVF_EXTS, HEADER_TIME_KEY_CANDIDATES, \
     DEFAULT_H5NAME, TIME_GROUPKEY, MAGNETIZATION_GROUPKEY